services:
  app:
    image: registry.sudhanshu.dev/auth_n_authz:1.0
    build: .
    ports:
      - "8080:8080"
    environment:
      JWT_SEC: ${JWT_SEC}
      REDIS_URI: redis://redis:6379
      AUTH_N_AUTHZ_DB_URL: ${AUTH_N_AUTHZ_DB_URL}
      AUTH_N_AUTHZ_DOMAIN: ${AUTH_N_AUTHZ_DOMAIN}
      AUTH_N_AUTHZ_PROTOCOL: ${AUTH_N_AUTHZ_PROTOCOL}
      AUTH_N_AUTHZ_LOG_FILE_NAME: ${AUTH_N_AUTHZ_LOG_FILE_NAME}
    depends_on:
      - redis
    networks:
      - local_net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - local_net

networks:
  local_net:
    driver: bridge
