name: Deploy Spring Boot (Build on VPS)

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1.0.0
        env:
          JWT_SEC: ${{ secrets.JWT_SEC }}
          AUTH_N_AUTHZ_DB_URL: ${{ secrets.AUTH_N_AUTHZ_DB_URL }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e

            # Fail fast if secrets are missing or empty
            : "${JWT_SEC:?JWT_SEC is missing}"
            : "${AUTH_N_AUTHZ_DB_URL:?AUTH_N_AUTHZ_DB_URL is missing}"

            cd ~/projects/auth_n_authz
            git fetch origin
            git reset --hard origin/master

            docker compose build
            docker compose up -d
            docker image prune -f
