name: Deploy Spring Boot (Build on VPS)

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printf "%s" "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on VPS
        env:
          JWT_SEC: ${{ secrets.JWT_SEC }}
          AUTH_N_AUTHZ_DB_URL: ${{ secrets.AUTH_N_AUTHZ_DB_URL }}
        run: |
          ssh -i ~/.ssh/id_ed25519 -o IdentitiesOnly=yes -T \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          set -e

          export JWT_SEC
          export AUTH_N_AUTHZ_DB_URL

          cd ~/projects/auth_n_authz 
          git fetch origin 
          git reset --hard origin/master 
          
          docker compose build 
          docker compose up -d 
          docker image prune -f

          EOF


